name: d7iiedorg
recipe: acquia
config:
  acli_version: latest
  ah_application_uuid: 6f9f27ed-0593-42f8-b43a-e0c3ec9329ab
  ah_site_group: iiedorg
  php: '7.4'
  webroot: docroot
services:
  appserver:
    overrides:
      environment:
        DRUSH_OPTIONS_ROOT: '/app/docroot'
        DRUSH_OPTIONS_URI: 'https://d7iiedorg.lndo.site'
  adminer:
    type: compose
    services:
      image: dehy/adminer
      command: '/bin/s6-svscan /etc/services.d'
    portforward: true
