<?php

/**
 * Implements hook_wysiwyg_editor_settings_alter()
 */
function iied_features_wysiwyg_editor_settings_alter(&$settings, $context) {

  // The $context variable contains information about the wysiwyg profile we're using
  // In this case we just need to check that the editor being used is ckeditor

  if ($context['profile']->editor == 'ckeditor') {

    $settings['removeFormatAttributes'] = 'class,style,lang,width,height,align,hspace,valign,target';
    $settings['pasteFromWordPromptCleanup'] = true;
 	$settings['allowedContent'] = true;
  }
}


/**
 * Implements hook_language_switch_links_alter
 *
 * Unset lang-switcher links for non-existent translations.
 */
function iied_features_language_switch_links_alter(array &$links, $type, $path) {
  $node = menu_get_object();
  if ($node) {
    // Unset lang-switcher links for non-existent translations
    foreach ($links as $langcode => &$link) {
      if (!isset($node->translations->data[$langcode])) {
        unset($links[$langcode]);
      }
      $link['attributes']['hreflang'] = $langcode;
    }
  }
  $term = menu_get_object('taxonomy_term', 2);
  if ($term) {
    // User is on a taxonomy term page
    foreach ($links as $langcode => &$link) {
      if (is_numeric(strpos(drupal_get_path_alias($links[$langcode]['href'], $langcode), 'taxonomy/term/'))) {
        // No translation exists as no alias has been created
        unset($links[$langcode]);
      }
      $link['attributes']['hreflang'] = $langcode;
    }
  }
  foreach ($links as $langcode => &$link) {
    switch ($langcode) {
      case 'en':
        $links[$langcode]['title'] = t('View this page in English');
        break;
      case 'de':
        $links[$langcode]['title'] = t('Diese Seite auf Deutsch anzeigen');
        break;
      case 'fr':
        $links[$langcode]['title'] = t('Voir cette page en français');
        break;
      case 'es':
        $links[$langcode]['title'] = t('Ver esta página en español');
        break;
      case 'pt':
      case 'pt-br':
      case 'pt-pt':
        $links[$langcode]['title'] = t('Veja esta página em Português');
        break;
      case 'zh-cn':
      case 'zh-hans':
        $links[$langcode]['title'] = t('以中文浏览此页');
        break;
    }
  }
}

/**
 * Implements hook_block_info().
 */
function iied_features_block_info() {
  $blocks['iied_features'] = array(
    // The name that will appear in the block list.
    'info' => t('Sharing links'),
    // Default setting.
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['iied_features_icons'] = array(
    // The name that will appear in the block list.
    'info' => t('Sharing icons'),
    // Default setting.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 * TODO: Add footer scope
*/

function iied_features_block_view($delta = '') {
  $block = array();
  $pageUrl = url(drupal_get_path_alias(current_path()), array('absolute' => TRUE));
  $title = drupal_get_title();
  $path = drupal_get_path('module', 'iied_features');
  switch ($delta) {
    case 'iied_features':
      $block['subject'] = t('Share this page');
      $block['content'] = array(
        '#markup' => iied_features_content($pageUrl, $title, true),
      );
      break;
    case 'iied_features_icons':
      $block['subject'] = t('Share this page');
      $block['content'] = array(
        '#markup' => iied_features_content($pageUrl, $title, false),
      );
      break;
  }
  drupal_add_css($path . "/iied_features.css");
  drupal_add_js(array('iiedFeatures' => array('pageUrl' => $pageUrl)), 'setting');
  drupal_add_js($path . '/iied_features.js', array('scope' => 'footer'));
  return $block;
}

function iied_features_content($lnk, $ttl, $linktext) {
  if ($linktext) {
    $twitter = '<li><button class="btn-share"><a class="share-twitter" target="_blank" href="https://twitter.com/share?text=' . urlencode($ttl) . ', via @IIED&url=' . $lnk . '" title="Tweet '. $ttl . '"><i class="twitter fa fa-twitter"></i><span class="icon-label">' . t("Tweet") . '</span></a></button></li>';
    $facebook = '<li><button class="btn-share"><a class="share-facebook" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=' . $lnk . '" title="Facebook '. $ttl . '"><i class="fa fa-facebook"></i><span class="icon-label">' . t("Share") . '</span></a></button></li>';
    $linkedin = '<li><button class="btn-share"><a class="share-linkedin" target="_blank" href="https://www.linkedin.com/sharing/share-offsite/?url=' . $lnk . '" title="LinkedIn '. $ttl . '"><i class="fa fa-linkedin"></i><span class="icon-label">' . t("Share") . '</span></a></button></li>';
    $email = '<li><button class="btn-share"><a class="share-email" title="Email '. $ttl . '" href="mailto:?subject=' . $ttl . '&body=' . t('I thought you might enjoy this from IIED:') . '%0D%0A%0D%0A' . $lnk .'"><i class="fa fa-envelope"></i><span class="icon-label">' . t("Email") . '</span></a></button></li>';
    $copy = '<li><button class="btn-share js-copy-btn"><a class="share-url" title="Copy link to '. $ttl . '" href="#"><i class="fa fa-link"></i>&nbsp;<span class="copylink">Copy&nbsp;link</span></a></button></li>';
    $print = '<li><button class="btn-share print-btn"><a class="share-print" title="Print/PDF" href="#" onclick="window.print();"><i class="fa fa-print"></i>&nbsp;<span class="printlink">Print/PDF</span></a></button></li>';
    $content = '<div class="iiedFeatures"><ul>' . $twitter . $facebook . $linkedin . $email . $copy . $print . '</ul></div>';
  }
  else {
    $twitter = '<li><button class="btn-share"><a class="share-twitter" target="_blank" href="https://twitter.com/share?text=' . urlencode($ttl) . ', via @IIED&url=' . $lnk . '" title="Tweet '. $ttl . '"><i class="twitter fa fa-twitter"></i></a></button></li>';
    $facebook = '<li><button class="btn-share"><a class="share-facebook" target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=' . $lnk . '" title="Facebook '. $ttl . '"><i class="fa fa-facebook"></i></a></button></li>';
    $linkedin = '<li><button class="btn-share"><a class="share-linkedin" target="_blank" href="https://www.linkedin.com/sharing/share-offsite/?url=' . $lnk . '" title="LinkedIn '. $ttl . '"><i class="fa fa-linkedin"></i></a></button></li>';
    $email = '<li><button class="btn-share"><a class="share-email" title="Email '. $ttl . '" href="mailto:?subject=' . $ttl . '&body=' . t('I thought you might enjoy this from IIED:') . '%0D%0A%0D%0A' . $lnk .'"><i class="fa fa-envelope"></i></a></button></li>';
    $content = '<div class="iiedFeatures"><ul>' . $email . $twitter . $facebook . $linkedin . '</ul></div>';
  }
  return $content;
}
