<?php

/**
 * @file
 * Remove path element from vertical tabs.
 */

/*
function iied_features_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#node_edit_form']) && $form['#node_edit_form']) {
	if ($form_id == 'blog_node_form' || $form_id == 'project_node_form' || $form_id == 'article_node_form' || $form_id == 'press_release_node_form') {
		$form['field_display_date']['#group'] = 'author';
		$form['path']['#group'] = '';
		$form['path']['#title'] = '';
		$form['path']['#collapsible'] = FALSE;
		$form['path']['#collapsed'] = FALSE;
		$protocol = isset($_SERVER['HTTPS']) ? 'https://' : 'http://';
		$hostname = $_SERVER['SERVER_NAME'];
		$form['path']['alias']['#title'] = t('Link: @baseurl/', array('@baseurl' => $protocol . $hostname));
	}	
  }
}
*/

/* 
 *Temp solution to allow anonymous users to search site users 
 

function iied_features_apachesolr_query_alter(DrupalSolrQueryInterface $query) {
  $query->removeFilterSubQueries();
  $subquery = apachesolr_drupal_subquery();
  $subquery->addFilter('hash', apachesolr_site_hash());
  $query->addFilterSubQuery($subquery);
}

*/


/**
 * Implements hook_wysiwyg_editor_settings_alter()
 */
function iied_features_wysiwyg_editor_settings_alter(&$settings, $context) {
 
  // The $context variable contains information about the wysiwyg profile we're using
  // In this case we just need to check that the editor being used is ckeditor
 
  if ($context['profile']->editor == 'ckeditor') {
 
    $settings['removeFormatAttributes'] = 'class,style,lang,width,height,align,hspace,valign,target';
    $settings['pasteFromWordPromptCleanup'] = true;
 	$settings['allowedContent'] = true;
  }
}


/**
 * Implements hook_language_switch_links_alter
 *
 * Unset lang-switcher links for non-existent translations.
 */
function iied_features_language_switch_links_alter(array &$links, $type, $path) {
  $node = menu_get_object();
  if ($node) {
    // Unset lang-switcher links for non-existent translations
    foreach ($links as $langcode => &$link) {
      if (!isset($node->translations->data[$langcode])) {
        unset($links[$langcode]);
      }
      $link['attributes']['hreflang'] = $langcode;
    }
  }
}

/**
 * Implements hook_node_view
 *
 * Redirect to language-neutral page when translation doesn't exist
 *
 * @param $node
 * @param $view_mode
 * @param $langcode
 */
function iied_features_node_view($node, $view_mode, $langcode) {
  // IF viewing full node
  if ($view_mode === 'full') {
    // AND IF not default language
    $default_languages = array('und', language_default('language'));
    if (!in_array($langcode, $default_languages)) {
      $node_languages = array_keys($node->translations->data);
      // AND IF not has translation in language
      if (!in_array($langcode, $node_languages)) {
        // THEN goto default language
        drupal_goto('node/'.$node->nid, array('language' => 'und'));
      }
    }
  }
}
