<?php


/**
 * Implements hook_wysiwyg_editor_settings_alter()
 */
function iied_features_wysiwyg_editor_settings_alter(&$settings, $context) {

  // The $context variable contains information about the wysiwyg profile we're using
  // In this case we just need to check that the editor being used is ckeditor

  if ($context['profile']->editor == 'ckeditor') {

    $settings['removeFormatAttributes'] = 'class,style,lang,width,height,align,hspace,valign,target';
    $settings['pasteFromWordPromptCleanup'] = true;
 	$settings['allowedContent'] = true;
  }
}


/**
 * Implements hook_language_switch_links_alter
 *
 * Unset lang-switcher links for non-existent translations.
 */
function iied_features_language_switch_links_alter(array &$links, $type, $path) {
  $node = menu_get_object();
  if ($node) {
    // Unset lang-switcher links for non-existent translations
    foreach ($links as $langcode => &$link) {
      if (!isset($node->translations->data[$langcode])) {
        unset($links[$langcode]);
      }
      $link['attributes']['hreflang'] = $langcode;
    }
  }
  $term = menu_get_object('taxonomy_term', 2);
  if ($term) {
    // User is on a taxonomy term page
    foreach ($links as $langcode => &$link) {
      if (is_numeric(strpos(drupal_get_path_alias($links[$langcode]['href'], $langcode), 'taxonomy/term/'))) {
        // No translation exists as no alias has been created
        unset($links[$langcode]);
      }
      $link['attributes']['hreflang'] = $langcode;
    }
  }
  foreach ($links as $langcode => &$link) {
    switch ($langcode) {
      case 'en':
        $links[$langcode]['title'] = t('View this page in English');
        break;
      case 'de':
        $links[$langcode]['title'] = t('Diese Seite auf Deutsch anzeigen');
        break;
      case 'fr':
        $links[$langcode]['title'] = t('Voir cette page en français');
        break;
      case 'es':
        $links[$langcode]['title'] = t('Ver esta página en español');
        break;
      case 'pt':
        $links[$langcode]['title'] = t('Veja esta página em Português');
        break;
      case 'zh-cn':
      case 'zh-hans':
        $links[$langcode]['title'] = t('以中文浏览此页');
        break;
    }
  }
}
